{"labels": [{"name": "feature", "value": "考勤管理"}, {"name": "story", "value": "考勤管理>打卡>外勤签到"}, {"name": "epic", "value": "泛微小e意图识别"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "subSuite", "value": "TestIntention"}, {"name": "suite", "value": "intention_test"}, {"name": "host", "value": "DESKTOP-NTA3Ax4"}, {"name": "thread", "value": "12740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.intention_test"}], "parameters": [{"name": "circle", "value": "{}"}], "stop": 1614231463665, "status": "broken", "start": 1614231463665, "statusDetails": {"message": "KeyError: 'text'", "trace": "self = <intention_test.TestIntention object at 0x00000212DFFCAA20>, circle = {}\n\n    @allure.story('考勤管理>打卡>外勤签到')\n    @pytest.mark.parametrize('circle', attendance_outside_sign_in)\n    def test_attendance_outside_sign_in(self, circle):\n        # 请求接口并获取返回的data\n>       request = request_get_ceshi(circle['text'])\nE       KeyError: 'text'\n\nTestCase\\intention_test.py:77: KeyError"}, "historyId": "6a4a6c04e366cfbbffe55f69a12fdf83", "uuid": "63a042f4-50d6-4c13-bbdb-5172eb4804ec", "name": "test_attendance_outside_sign_in[circle1]", "testCaseId": "17ca1a72459dad0b229994eb07805ef5", "fullName": "TestCase.intention_test.TestIntention#test_attendance_outside_sign_in"}